myshop/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail'),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/payment/urls.py
from django.urls import path
from . import views, webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

myshop/payment/views.py
from django.shortcuts import render


from decimal import Decimal
import stripe
from django.conf import settings
from django.shortcuts import render, redirect, reverse,get_object_or_404
from orders.models import Order

# create Stripe instance
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    """ Payment presentation.
    In the view, a session is created with data about the user,
    goods, and their cost. Redirect to the successful payment page
    or to the transaction cancellation page. """
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))
        # Stripe of payments session data
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }
        # add order items to the Strip checkout session
        for item in order.items.all():
            session_data['line_items'].append({'price_data': {'unit_amount': int(item.price * Decimal('100')),
                                                              'currency': 'usd',
                                                              'product_data': {'name': item.product.name,},
                                                              },
                                               'quantity': item.quantity})
            # Stripe coupon
            if order.coupon:
                stripe_coupon = stripe.Coupon.create(name=order.coupon.code,
                                                     percent_off=order.discount,
                                                     duration='once')
                session_data['discounts'] = [{'coupon': stripe_coupon.id}]
        # create payment session
        session = stripe.checkout.Session.create(**session_data)
        # redirect to Strip payment form
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html', locals())


def payment_completed(request):
    """ Display template on successful payment. """
    return render(request, 'payment/completed.html')

def payment_canceled(request):
    """ Displaying a template when a payment fails
     or an operation is cancelled. """
    return render(request, 'payment_canceled.html')

myshop/payment/templates/payment/canceled.html
{% extends 'shop/base.html' %}

{% block title %}Payment canceled{% endblock title %}

{% block content %}
<h1>Your payment has not been processed</h1>
<p>There was a problem processing your payment.</p>
{% endblock content %}

myshop/payment/templates/payment/completed.html
{% extends 'shop/base.html' %}

{% block title %}Payment successful{% endblock title %}

{% block content %}
<h1>Your payment was successful</h1>
<p>Your payment has been processed successfully.</p>
{% endblock content %}

myshop/payment/templates/payment/process.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}Pay your order{% endblock title %}

{% block content %}
<h1>Order summary</h1>
<table class="cart">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% for item in order.items.all %}
            <tr class="row{% cycle '1' '2' %}">
                <td>
                    <img src="{% if item.product.image %}{{ item.product.image }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                </td>
                <td>{{ item.product.name }}</td>
                <td class="num">${{ item.price }}</td>
                <td class="num">{{ item.quantity }}</td>
                <td class="num">${{ item.get_cost }}</td>
            </tr>
        {% endfor %}
        {% if order.coupon %}
        <tr>
            <td>Subtotal</td>
            <td colspan="3"></td>
            <td class="num">
                ${{ order.get_total_cost_before_discount|floatformat:2 }}
            </td>
        </tr>
        <tr>
            <td>"{{ order.coupon.code }}" coupon ({{ order.discount }}% off)</td>
            <td colspan="3"></td>
            <td class="num neg">- ${{ order.get_discount|floatformat:2 }}</td>
        </tr>
        {% endif %}
        <tr class="total">
            <td colspan="3">Total</td>
            <td class="num">${{ order.get_total_cost|floatformat:2 }}</td>
        </tr>
    </tbody>
</table>
<form action="{% url 'payment:process' %}" method="post">
    <input type="submit" value="Pay now">
    {% csrf_token %}
</form>
{% endblock content %}